"""Modify aAdmins model

Revision ID: 109b95c454b7
Revises: 23676b394e2d
Create Date: 2023-11-12 14:39:46.895891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109b95c454b7'
down_revision = '23676b394e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('restaurant_date_registered',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_date_registered', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_date_registered')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('review_date')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('restaurant_date_registered',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
