"""Changed is_admin to boolean

Revision ID: 650534c28d6e
Revises: 91ef5f280df5
Create Date: 2023-11-12 12:12:21.863676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650534c28d6e'
down_revision = '91ef5f280df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
