"""Modify aAdmins model

Revision ID: dd3650221401
Revises: bd6efb52f352
Create Date: 2023-11-12 13:10:02.796749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3650221401'
down_revision = 'bd6efb52f352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('admins_username_key', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('admins_username_key', ['username'])

    # ### end Alembic commands ###
